### ISSUE TITLE
Twitter embeds aren't responsive

### ISSUE THREAD

**Issue by ofadam** [s9e/phpbb-ext-mediaembed#1]
Is there a way to make Twitter embeds responsive using this plugin? Currently, they are cut in half on small viewports:

http://www.pjstarforums.com/viewtopic.php?f=63&t=98419&hilit=twitter&start=525#p1410952

**Comment by JoshyPHP** [comment]
It's not currently a feature if that's what you're asking. What you can do is add something like this to your forum's CSS:

``` css
iframe, embed, object { max-width: 100% }
```

The Twitter iframe's height is already responsive, if you limit its width you should be alright.

**Comment by ofadam** [comment]
That indeed worked – would there be a way to incorporate it into the mod at some point?

**Comment by JoshyPHP** [comment]
It's likely. I'd have to look up how extensions can add CSS in phpBB first.

**Comment by JoshyPHP** [comment]
All embeds should be responsive now.
