### ISSUE TITLE
Imgur embedding is not responsive

### ISSUE THREAD

**Issue by cleary** [s9e/phpbb-ext-mediaembed#10]
Hi again, 
I know this was reported previously [for twitter](https://github.com/s9e/phpbb-ext-mediaembed/issues/1), so I thought it was worth reporting that the imgur embedding is not responsive either:

![screenshot from 2017-07-21 14-57-31](https://user-images.githubusercontent.com/2577966/28449697-4f98e146-6e25-11e7-971c-38ebea771263.png)

Thanks -

**Comment by JoshyPHP** [comment]
What Imgur URL do you try to embed? Do you have a public page showing the result?

**Comment by cleary** [comment]
Public Page:
http://ozbassforum.com/viewtopic.php?f=30&t=22546

**Comment by JoshyPHP** [comment]
I'll look into it. In the meantime, I believe you can limit the size in CSS with `iframe { max-width:100% }`

**Comment by cleary** [comment]
Thanks a lot :)

**Comment by JoshyPHP** [comment]
As per https://github.com/s9e/TextFormatter/commit/2d3cc9ba9a23f278b1cc6f33acfe97fe13460bfe the Imgur embed should now be limited to 100% of the available width by default. The change will trickle down to your phpBB installation at some point in the future, although I can't say when exactly.
