### ISSUE TITLE
Show Version in Backend (Green/Red) including Link to update

### ISSUE THREAD

**Issue by bug-i** [s9e/phpbb-ext-mediaembed#11]
Could you adjust the behaviour of the extension in the backend. Usually all other extension are indicating if they are up to date or outdated with green/red. 

Also switching to a version number instead of timestamp seems to be more common.
Thanks!

![2017-09-20 14_25_46-erweiterungen verwalten](https://user-images.githubusercontent.com/29623218/30643538-acd69d2a-9e0f-11e7-8ee9-50c7a5300c25.png)

**Comment by JoshyPHP** [comment]
The version checker works fine in 3.1 but something changed in 3.2 that makes phpBB reject version numbers that don't conform to their format. That's something that would need to be changed in phpBB.

The alternative would be to change the version number to 20170724.0.0 but that seems unnecessarily complicated.

**Comment by Galixte** [comment]
Yes useless.

@bug-i same answer like your same question on other repository, watch this repository in your WatchList. ;)
