### ISSUE TITLE
Facebook live videos

### ISSUE THREAD

**Issue by CHB83** [s9e/phpbb-ext-mediaembed#12]
Hi all

Well, I don't know if it's a true issue, but I would like to share with you an anormal behavior of the extension, especially with Facebook videos.

FB standard videos works very well on my board with and without [media] BBCode, but "live" video are not working, even if the videos are not alive anymore.

I opened a thread on phpBB support board : https://www.phpbb.com/customise/db/extension/mediaembed/support/topic/183061 with a screenshot.

If it can help :)

Regards,

Charles

**Comment by JoshyPHP** [comment]
What URL did you try? Some live videos are set to expire so if it's not working now, it won't be displayed.

**Comment by CHB83** [comment]
This one for example : https://www.facebook.com/jyybeyy.thibaudeau/videos/10212145366126937/

**Comment by JoshyPHP** [comment]
When I click on this link, all I get is this:

> **⚠ Sorry, this content isn't available right now**
> ***
> The link you followed may have expired, or the page may only be visible to an audience you're not in.

**Comment by CHB83** [comment]
Ok. Finally I understand : the visibility of the video is "friends only", not public ... I didn't remember that you can choose the scope of a publication (public/friends/some friends only, etc.).

I think it's the right answer, and it's not a bug.

**Comment by JoshyPHP** [comment]
I guess that explains it, thanks for the heads up.
