### ISSUE TITLE
(Mobile) Scrolling issues when multiple images are linked in a row

### ISSUE THREAD

**Issue by cleary** [s9e/phpbb-ext-mediaembed#14]
Hi again, 
We're having some issues when multiple images are linked in a row (ie more than will fit on the screen at a time). With such a post ([example](http://www.ozbassforum.com/viewtopic.php?f=22&t=23109)) scrolling on mobile gets a little tricky. 
The scroll events seem to be getting captured in the iframe, so in order to scroll the page, you have to very carefully find the spaces between the images, if any exist.

So I'm hoping that there's a way to work around this so that, on mobile at least, you can make sure that phpbb deals with the scroll event, and not the iframe. 
Since the iframes are resized to fit the theme, there's no particular use for the scroll inside the iframe anyway - obviously until you zoom. It might make implement the iframe scroll block on mobile only?

Thanks for your consideration -

**Comment by cleary** [comment]
I've done a bit more testing, it appears there is different behaviour between browsers:
Firefox mobile = NO problem 
Chrome mobile = Problem
Safari mobile = Problem

**Comment by Galixte** [comment]
So, webkit problem.

@JoshyPHP, could you take a look, please?

**Comment by JoshyPHP** [comment]
I don't have a WebKit implementations to test it on but either way I don't think there's anything any of us can do. GoogleDrive's picture viewer uses scrolling events to implement their own scrolling/zooming feature; It causes some issues when trying to scroll the page while the GoogleDrive viewer is in focus, even on desktop.

The iframes are already set to disable scrolling at the iframe level but the scrolling events are captured by the document inside the iframe. It should be impossible to change that from the outside.

Maybe your browser/OS supports some kind of multi-fingers unconditional scrolling? If not, the only workaround would be to include those pictures as simple images, bypassing GoogleDrive's viewer. Or you can use CSS in your site's theme to reduce the size of the GoogleDrive embed and leave some room for touch events outside of the viewer. Maybe something like that:

```css
@media (max-width: 800px)
{
	[data-s9e-mediaembed="googledrive"]
	{
		max-width: 90% !important;
	}
}
```

**Comment by cleary** [comment]
Thanks @JoshyPHP , as always - appreciate the timely response and info. We'll probably give the css mod a go :)
