### ISSUE TITLE
builtin filer urldecode break images on phpbb

### ISSUE THREAD

**Issue by MoleDJ** [s9e/phpbb-ext-mediaembed#15]
If you have the extension installed and you do a post with an [img] like this, the extension break the image as it urldecode. http://www.theroyalwindsorwebsite.com/images01/LocalEvents/Schools/StStephens%3FPlayHA.jpg

**Comment by JoshyPHP** [comment]
I don't know what you're talking about. How can I reproduce this issue? What do I need to put in the text box?
