### ISSUE TITLE
Instagram support

### ISSUE THREAD

**Issue by Sicos1977** [s9e/phpbb-ext-mediaembed#16]
Hi,

First of all... great work on this phpBB extension. Keep up the good work.

Now the question :-) ... is it possible to support embedding of Instagram for URL's like this?

https://www.instagram.com/hamsters.in.crime/

Greetings,
Kees van Spelde

**Comment by JoshyPHP** [comment]
No, as far as I'm aware, Instagram does not offer a way to embed a whole board, only individual posts such as https://www.instagram.com/p/BbxijIPlZu3/?taken-by=hamsters.in.crime

**Comment by Sicos1977** [comment]
Ah ok... thanks for the quick reply
