### ISSUE TITLE
How to add new media  embed

### ISSUE THREAD

**Issue by saper82** [s9e/phpbb-ext-mediaembed#18]
Hi

I have a link `https://www.cda.pl/video/xyz`

and I want this embed

`<iframe src="http://ebd.cda.pl/620x368/xyz" width="620" height="368" style="border:none;" scrolling="no" allowfullscreen name="v2"></iframe>`

CDA is the most popular video site in Poland.

**Comment by JoshyPHP** [comment]
There's nothing in this extension to do that. You'd have to write your own extension and add the site using [this tutorial](http://s9etextformatter.readthedocs.io/Plugins/MediaEmbed/Add_custom/).
