### ISSUE TITLE
YouTube Problem

### ISSUE THREAD

**Issue by Leinad4Mind** [s9e/phpbb-ext-mediaembed#19]
This ext doesnt parse this url:

https://www.youtube.com/embed/chElHV99xak?start=53&end=59

**Comment by JoshyPHP** [comment]
The extension doesn't take iframe URLs, you'll need to use the video's canonical URL, e.g. https://www.youtube.com/watch?v=chElHV99xak

**Comment by Leinad4Mind** [comment]
But how can I have then a start and end on a video? Like the example above?

**Comment by JoshyPHP** [comment]
There's no support for an end timestamp. For the start timestamp, it's in the canonical URL if you right-click on the player it'll give you an URL for it, e.g. https://youtu.be/chElHV99xak?t=53
