### ISSUE TITLE
GooglePlus Events

### ISSUE THREAD

**Issue by PROVRS** [s9e/phpbb-ext-mediaembed#2]
Hello. Google+ events are not showing in forum. Neither posts about events. Facebook events are working ok. 
Can you add this please?

**Comment by JoshyPHP** [comment]
If you post an example of each kind of URL then I'll definitely consider it.

**Comment by PROVRS** [comment]
Sorry, didn't want to look like an ad.
So events like this: https://plus.google.com/events/c5j1q6a1m9oqs66rl......

**Comment by JoshyPHP** [comment]
Ok, I looked into it and they simply cannot be embedded, sorry. They're just not supported by Google+.

https://developers.google.com/+/web/embedded-post/#supported_posts

**Comment by PROVRS** [comment]
Thank you for your time. Sorry to hear that google are not supporting it.
Keep up the good work! 
Cheers :)

**Comment by JoshyPHP** [comment]
Cheers ;)
