### ISSUE TITLE
Embed Spotify without cover art ("view=coverart&" in the URL)

### ISSUE THREAD

**Issue by ImAiiR** [s9e/phpbb-ext-mediaembed#20]
Hey, love the extension, works great on my site. Was trying to mess with the rendering.php to remove the "view=coverart&" from the Spotify embeds, so it would instead show the track list.

I removed the 2 instances I could find, but when testing it out, it still puts the "view=coverart&" in the embed URL.

No need to push any type of update, just wanted to know if there was something I could modify to get the desired result?

**Comment by JoshyPHP** [comment]
Would you mind posting the kind of URL that should display a track list? That's how the other similar media sites work so if I can, I'd like to display the cover art for singles and the list of tracks for playlists/tracklists.

If you want to modify a template, you can create an extension and use something like that:

```php
use Symfony\Component\EventDispatcher\EventSubscriberInterface;
class listener implements EventSubscriberInterface
{
	public static function getSubscribedEvents()
	{
		return ['core.text_formatter_s9e_configure_after' => ['afterConfigure', -1]];
	}
	public function afterConfigure($event)
	{
		$tag = $event['configurator']->tags['SPOTIFY'];

		// As a string
		$tag->template = str_replace('view=coverart&amp;', '', $tag->template);

		// As a DOM document
		$dom = $tag->template->asDOM();
		// ...
		$dom->saveChanges();
	}
}
```

I recommend modifying the template using DOM operations rather than string manipulation. It's way more verbose but also more reliable and future-proof.

http://s9etextformatter.readthedocs.io/Templating/Modify_a_template/

**Comment by ImAiiR** [comment]
When posting this link
https://open.spotify.com/album/0XMkrjoxpwaGgb6MYgv2gA

it embeds with this link
https://open.spotify.com/embed?view=coverart&uri=spotify:album:0XMkrjoxpwaGgb6MYgv2gA

I'd like it to embed with this instead
https://open.spotify.com/embed?uri=spotify:album:0XMkrjoxpwaGgb6MYgv2gA

I've seen in the rendering.php file, that it goes to "src=" https://embed.spotify.com/?view=coverart&uri=' " twice, so I thought modifying those instances to " https://embed.spotify.com/?uri=' " would give me the result I was looking for. I also couldn't seem to find anything else that references to adding the "view=coverart&" to the URL.

I'm trying to edit the latest release of the extension, so every other embed works how it does already, but get Spotify embeds to do what I'm looking for.

**Comment by JoshyPHP** [comment]
I don't know which file you're trying to edit but those changes will be overwritten the next time you update phpBB or maybe the next time the cache is refreshed. If you want to permanently change the way something works, you have to do it via your own extension.

I'm going to update the Spotify embed to use their latest player. Future versions will display the track list where applicable.
