### ISSUE TITLE
Add Support for Google Photos

### ISSUE THREAD

**Issue by MariusMasalar** [s9e/phpbb-ext-mediaembed#3]
I've been asked by a few members if it would be possible to add support for the new Google Photos—they use it to share photos and, of course, right now there's no native embed for them.

Not sure how feasible it is but I figured I'd ask on their behalf!

**Comment by JoshyPHP** [comment]
[Last time I checked](https://xenforo.com/community/threads/s9e-media-bbcodes-pack.61883/page-86#post-944976), Google Photos didn't provide a way to embed their content. If you post an example URL, I'll give it another look.

**Comment by MariusMasalar** [comment]
I thought that might be the case. Here's an example just in case there's some way to work around it:

https://goo.gl/photos/9y7W8zcP9BHSmHMK9

Thanks for trying! :)

**Comment by cleary** [comment]
@MariusMasalar 
I'm late to the party, but there is a workaround for this:
In Google Drive -> Settings -> General -> Create a Google Photos folder

This will show a Google Photos folder in Drive.
Then you can use the Drive share api to get a url that works with this plugin
