### ISSUE TITLE
soundcloud tracklist, fail in phpbb3.1

### ISSUE THREAD

**Issue by deejayses** [s9e/phpbb-ext-mediaembed#6]
hello, from time I used this plugin, works very well with all current multimedia formats.
But I have a problem with the track listing for soundcloud .
This is not displayed correctly
The URL is not working soundcloud

https://soundcloud.com/stereoproductions/sets/sp186-balearica-2016-by-chus-and-ceballos

And this post the link displayed incorrectly.
I've checked permissions and I think that is not the problem, you can guide me ?

http://deejays.es/phpBB3/escucha-los-temas-de-balearica-2016-de-chus-y-ceballos-183#p570

![sound](https://cloud.githubusercontent.com/assets/20374144/16709804/a8d7c3fe-461b-11e6-9d08-b5cacebea7ba.png)

**Comment by JoshyPHP** [comment]
SoundCloud changed something in their embedded player that is related to sets. The new update should fix your issue.

You'll see the list of tracks but none will be selected by default. If you edit the original post and change it, it will be reparsed and the player will have a default track selected. In other words, it will look better.

**Comment by deejayses** [comment]
Thanks for your quick response and modification.
I updated and working properly aunqe if the default image 1
regards
