### ISSUE TITLE
Video (MLB, etc.)

### ISSUE THREAD

**Issue by tony23456** [s9e/phpbb-ext-mediaembed#7]
Unable to embed this type of video:

http://web.yesnetwork.com/shared/video/embed/embed.html?content_id=1190113083&width=400&height=224&property=yesnetwork

What can I do to allow this to embed.

Thanks.

**Comment by JoshyPHP** [comment]
This isn't a supported site. There's nothing you can do really, sorry.

**Comment by tony23456** [comment]
Any idea where I can get a solution? thanks.

**Comment by JoshyPHP** [comment]
Since you're using phpBB you should try making a custom BBCode for it. Of course it won't automatically embed the video but you'll be able to use the custom BBCode to embed them yourself.
