### ISSUE TITLE
not an issue, more of a request

### ISSUE THREAD

**Issue by ciscoa007** [s9e/phpbb-ext-mediaembed#8]
this isn't really an issue, it's more of a feature request. Lets say people want to resize posted images open up with either lightbox, highslide extensions out there by just posting the link to the image, this would be a big use and great addition to the extension.

**Comment by JoshyPHP** [comment]
The extension only handles embeds from third-party sites. What you describe is more of an enhancement to the post editor. That would be better handled by a separate extension.

**Comment by ciscoa007** [comment]
sorry i meant images linked from third party sites, not posted images.

**Comment by JoshyPHP** [comment]
Even for third-party content, it's more of a user interface thing and would be better handled separately.
