### ISSUE TITLE
Some Google Drive formatted sharing links don't work

### ISSUE THREAD

**Issue by cleary** [s9e/phpbb-ext-mediaembed#9]
Hi, 
Thanks for such a great plugin - a forum I frequent has been hit badly by photobucket changing their external hosting policy, and this plugin has made a lot of our users lives much easier.

I've discovered this morning that google drive provides two different url formats for sharing, and your plugin only handles one of them. 

Example 1 (doesn't work): 
1. Open Google Drive in desktop browser
2. In file browser view (ie not preview mode), right click picture and choose "Get Shareable Link"
3. The pasted link then looks like: 
  https://drive.google.com/open?id=1TAnofDHLM-Mreaju0l3--9SQAESEIpD9AA
4. (Doesn't work)

Example 2 (works):
1. Open Google Drive in desktop browser
2. In file browser view (ie not preview mode), right click picture and choose "Share"
3. The link to copy then looks like:
  https://drive.google.com/file/d/1TAnofDHLM-Mreaju0l3--9SQAESEIpD9AA/view?usp=sharing
4. (Works)

It'd be fantastic if you could handle/reformat the non-working url - 
Thanks a lot -

**Comment by JoshyPHP** [comment]
I added support for this kind of links yesterday in https://github.com/s9e/TextFormatter/commit/2074eeabcef50193b8edb0bed827b665fdb9b39e

However, it will take some time before this change becomes effective in the phpBB extension. Most likely, you will have to wait for 3.2.2.
